# Generated by Django 4.0.3 on 2022-04-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default='', max_length=10)),
                ('Address', models.CharField(default='', max_length=50)),
                ('concat', models.IntegerField(default='', max_length=20)),
                ('mail', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
