# Generated by Django 4.0.3 on 2022-04-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createparents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=20)),
                ('secondname', models.CharField(default='', max_length=15)),
                ('username', models.CharField(default='', max_length=15)),
                ('mail', models.EmailField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='', max_length=20)),
                ('Secondname', models.CharField(default='', max_length=15)),
                ('mail', models.EmailField(default='', max_length=50)),
                ('Dob', models.DateField(max_length=20)),
                ('Age', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('Address', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
