# Generated by Django 4.0.3 on 2022-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_alter_createparents_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_type', models.CharField(choices=[(1, 'admin'), (2, 'Staff'), (3, 'parent')], default=1, max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='datejoined')),
                ('address', models.CharField(blank=True, max_length=150)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_active', 'In_Active'), ('waillist', 'Waitlist'), ('prospects', 'Prospects'), ('toured', 'Toured'), ('applied', 'Applied')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
