# Generated by Django 4.0.3 on 2022-04-30 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_app', '0008_teacherextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_active', 'In_Active'), ('waillist', 'Waitlist'), ('prospects', 'Prospects'), ('toured', 'Toured'), ('applied', 'Applied')], max_length=10)),
                ('Dob', models.DateField(max_length=20)),
                ('Age', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('mobile', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
