# Generated by Django 4.0.3 on 2022-04-30 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_alter_teacherextra_mobile_studentextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='joindate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
