# Generated by Django 4.0.3 on 2022-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0012_studentextra_parentname_alter_customuser_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_image/')),
            ],
        ),
    ]
